Citizen.CreateThread(function() -- Looks for gameName in the vehicles.meta.

	--[SADCR Vehicles]--
	AddTextEntry('coach', 'Prison Coach')
	AddTextEntry('dcrfpiu', 'DOC FPIU')
	AddTextEntry('dcrspeedo', 'DOC Transport Speedo')

	--[LSPD / BCSO Vehicles]--
	AddTextEntry('pdalamo', 'Police Alamo')
	AddTextEntry('pdbike', 'Police Moto Unit')
	AddTextEntry('pdbuffalo', 'Police Buffalo')
	AddTextEntry('pdbuffalo2', 'Police Buffalo S')
	AddTextEntry('pdscout', 'Police Scout')
	AddTextEntry('pdstanier', 'Police Stanier')
	AddTextEntry('pdtorence', 'Police Torence')
	AddTextEntry('pdfugitive', 'Police Fugitive')
	AddTextEntry('umkalamo', 'Unmarked Alamo')
	AddTextEntry('umkbuffalo', 'Unmarked Buffalo')
	AddTextEntry('trualamo3', 'Police Slicktop Alamo')

	--[SASP Vehicles]--
	AddTextEntry('spalamo', 'State Police Alamo')
	AddTextEntry('spbike', 'State Police Moto Unit')
	AddTextEntry('spbuffalo', 'State Police Buffalo')
	AddTextEntry('spbuffalo2', 'State Police Buffalo S')
	AddTextEntry('spscout', 'State Police Scout')
	AddTextEntry('spstanier', 'State Police Stanier')
	AddTextEntry('sptorence', 'State Police Torence')
	AddTextEntry('spfugitive', 'State Police Fugitive')
	AddTextEntry('sptrualamo3', 'State Police Slicktop Alamo')

	--[LSFD / BCFD Vehicles]--
	AddTextEntry('lsfd2', 'EMS Squad')
	AddTextEntry('lsfd3', 'EMS Bison Ambulance')
	AddTextEntry('lsfd4', 'EMS Van Ambulance')
	AddTextEntry('bcfdbat', 'EMS Command Alamo')
	AddTextEntry('lsfdcmd', 'EMS Command Bison')
	AddTextEntry('lsfdbuffalo', 'EMS Command Buffalo')
	AddTextEntry('lsfdtruck', 'EMS Fire Engine')
	AddTextEntry('emsspeedo', 'EMS Speedo Ambulance')

	--[LSMS Vehicles]--
	AddTextEntry('lsmsgresley', 'EMS Gresley')
	AddTextEntry('lsmsspeedo', 'EMS Coroner')

	--[SAPR Vehicles]--
	AddTextEntry('pdcara', 'Police Caracara')
	AddTextEntry('pdscout', 'Police Scout')
	AddTextEntry('pdbuffalo2', 'Police Buffalo S')
	AddTextEntry('pdmesa', 'Park Ranger Mesa')

	--[Biker Vehicles]--
	AddTextEntry('bluestar', 'Bluestar Custom Chopper')
	AddTextEntry('blackhorse', 'Harley-Davidson Blackhorse')
	AddTextEntry('challengerb', 'Indian Challenger')
	AddTextEntry('maya', 'Maya Custom Chopper')
	AddTextEntry('beaver', 'Indian Beaver')
	AddTextEntry('chingon', 'Chingon Custom Chopper')

	--[ Imports ]--
	AddTextEntry('GNX', 'Buick GNX')
	AddTextEntry('chevelle', 'Chevrolet Chevelle SS')
	AddTextEntry('charger', 'Dodge Charger')
	AddTextEntry('charger2', 'Dodge Charger R/T')
	AddTextEntry('charger3', 'Dodge Charger SuperBee')
	AddTextEntry('corvette', 'Corvette C8')
	AddTextEntry('corvette2', 'Chevrolet C7 Z06')
	AddTextEntry('corvette3', 'Corvette Stingray')
	AddTextEntry('civtaurus', 'Ford Taurus')
	AddTextEntry('demon', 'Dodge Challenger')
	AddTextEntry('e60', 'BMW M5')
	AddTextEntry('viper', 'Dodge Viper ACR')
	AddTextEntry('royallancer', 'Dodge Royal Lancer')
	AddTextEntry('mustang2', 'Ford Mustang Fastback')
	AddTextEntry('ss7', 'Saleen S7')
	AddTextEntry('rx7v', 'Mazda RX7 Veilside')
	AddTextEntry('starion', 'Mitsubishi Starion')
	AddTextEntry('mitsugto', 'Mitsubishi 3000GT')
	AddTextEntry('elegyrh72', 'Elegy RH-7')
	AddTextEntry('skyline', 'Nissan Skyline R-34 GT-R')
	AddTextEntry('r35gtr', 'Nissan R-35 GT-R')
	AddTextEntry('fz50', 'Suzuki FZ-50')
	AddTextEntry('gsxr', 'Suzuki GSX-R')
	AddTextEntry('hayabusa', 'Suzuki Hayabusa')
	AddTextEntry('ae86', 'Toyota Trueno')
	AddTextEntry('supra2', 'Toyota Supra')
	AddTextEntry('supra4', 'Toyota Celica-Supra')
	AddTextEntry('rmodgt63', 'Mercedez-Benz AMG GT63s')
	AddTextEntry('2017chiron', 'Bugatti Chiron')
	AddTextEntry('2019chiron', 'Bugatti Chiron Super Sport')
	AddTextEntry('divo', 'Bugatti Divo')
	AddTextEntry('eb110', 'Bugatti EB-110')
	AddTextEntry('f1', 'McLaren F1')
	AddTextEntry('f8t', 'Ferrari F8 Tributo')
	AddTextEntry('amggt', 'Mercedez-Benz AMG GT')
	AddTextEntry('911ts', 'Porsche 911 Turbo S')
	AddTextEntry('speedster', 'Porsche 911 Speedster')
	AddTextEntry('huracan2', 'Lamborghini Huracan')
	AddTextEntry('mp412c', 'McLaren MP4-12C')
	AddTextEntry('impala', 'Chevy Impala 9th Gen')
	AddTextEntry('impala2', 'Chevy Impala 7th Gen')
	AddTextEntry('impala3', 'Chevy Impala 6th Gen')
	AddTextEntry('impala4', 'Chevy Impala 6th Gen Beater')
	AddTextEntry('accord2', 'Honda Accord Mugen')
	AddTextEntry('exige', 'Lotus Elise')
	AddTextEntry('miata', 'Mazda MX-5 Miata')
	AddTextEntry('models', 'Tesla Model S')
	AddTextEntry('polestar', 'Volvo Polestar')
	AddTextEntry('r8', 'Audi R8')
	AddTextEntry('458italia', 'Ferrari 458 Italia')
	AddTextEntry('812sf', 'Ferrari 812 Superfast')
	AddTextEntry('zonda2', 'Pagani Zonda R')
	AddTextEntry('huayra', 'Pagani Huayra')
	AddTextEntry('protoz', 'Proto Z')
	AddTextEntry('g65', 'Mercedes-Benz AMG G65')
	AddTextEntry('ram2500', 'Dodge Ram 2500')
	AddTextEntry('ram2500lifted', 'Dodge Ram 2500 Lifted')
	AddTextEntry('diablo', 'Lamborghini Diablo SV')
	AddTextEntry('mgt', '2015 Mustang GT')
	AddTextEntry('zagato', 'Aston Martin Vanquish Zagato')
	AddTextEntry('zrgpr', 'ZR350 ReMaul')
	AddTextEntry('bansheeas', 'Banshee Alien Style')
	AddTextEntry('gauntletctx', 'Gauntlet Hellfire CTX')
	AddTextEntry('stratumc', 'Zircoflow Stratum')
	AddTextEntry('roxanne', 'Annis Roxanne')
	AddTextEntry('buffaloh', 'Buffalo Hellhound')
	AddTextEntry('ariant', 'Karin Ariant')
	AddTextEntry('nexus', 'Dinka Nexus')
	AddTextEntry('sunrise1', 'Miabatsu Sunrise R')
	AddTextEntry('superd3', 'Super Diamond S')
	AddTextEntry('vigeronew', 'Vigero VL1')
	AddTextEntry('aventsvjr', 'Lamborghini Aventador SVJ')
	AddTextEntry('bt62r', 'Brabham BT62R')
	AddTextEntry('jesko', 'Koenigsegg Jesko')
	AddTextEntry('pgt3', 'Porsche GT3RS')
	AddTextEntry('roma20', 'Ferrari Roma')
	AddTextEntry('rs6avant20', 'Audi RS6 Avant')
	AddTextEntry('wheelchair', 'Emergency Wheelchair')
	AddTextEntry('zerouno', 'Italdesign Zerouno')
	AddTextEntry('brz13', 'Subaru BRZ')
	AddTextEntry('macan', 'Porsche Macan')

	--[Miscellaneous]--
	--[GTA V]--
	AddTextEntry('graintrailer', 'Grain Trailer')
	AddTextEntry('graintraile', 'Grain Trailer')
	AddTextEntry('docktrailer', 'Dock Trailer')
	AddTextEntry('proptrailer', 'Prop Trailer')
	AddTextEntry('tanker2', 'Fuel Trailer')
	AddTextEntry('tanker', 'Tanker Trailer')
	AddTextEntry('freighttrailer', 'Freight Trailer')
	AddTextEntry('freighttrai', 'Freight Trailer')
	AddTextEntry('Voodoo', 'Voodoo Custom')
	AddTextEntry('Voodoo2', 'Voodoo')

	--[ Commercial ]--
	AddTextEntry('nspeedo', 'Speedo Van')
	AddTextEntry('nspeedo2', 'Speedo Van')
	AddTextEntry('taco2', 'Frijoles Truck')
	AddTextEntry('redjb', "Teddy's Seajet")

end)